### PR TITLE
OnDiskSM: Consistency check that only reached SS get applied

### LINKED ISSUE #156: OnDiskSTM: Inconsistent OnDiskIndex during node start will silently be ignored
If an OnDiskSTM returns during the open an old index (let's say index=33) and the latest snapshot is on a newer index e.g. 50, this inconsistency will silently be ignored and assumed the OnDiskSTM is on 50. Therefore newer entries (e.g. with index=51, 52,...) will be recovered as it is assumed the STM is on index 50.
The node will just start fine and begin working with the old OnDiskSTM and and applying newer indexes. Which results in a gab of data.

It seems like one of the problems is that a dummy snapshot is just applied without any checks here:

https://github.com/lni/dragonboat/blob/6dcfdf3d07c56f42a8bf93893d618e8d6188d85e/internal/rsm/statemachine.go#L330-L333

### Dragonboat version
3.3.0

### Expected behavior

Starting of the node should fail, because the OnDiskSTM is on an older index from which a recovery is not possible anymore.

### Actual behavior

Inconsistent OnDisk index is ignored and normal operation will start with a gap on the on disk data. 

### Steps to reproduce the behavior

Use OnDisk Example adjust to code to a one node cluster only and put key values until at least one snapshot has been created. Afterwards adjust the code to return index 1 on opening. Then start the node again and see that the node starts just fine.

### PR DESCRIPTION
**Pull request by stffabi**
Fixes #156

### CODE REVIEW

File: internal/rsm/statemachine.go [hunk 1]
```diff
@@ -341,12 +344,28 @@ func (s *StateMachine) recover(ss pb.Snapshot, init bool) error {
...
 		s.applyOnDisk(ss, init)
 	} else {
+		// A snapshot can only be applied if we have at least the OnDiskIndex of the snapshot reached.
+		// If we have not reached it, a recovery above would be needed.
+		if init {
+			if ss.OnDiskIndex > s.onDiskInitIndex {
+				plog.Panicf("%s, ss.OnDiskIndex (%d) > s.onDiskInitIndex (%d)",
+					s.id(), ss.OnDiskIndex, s.onDiskInitIndex)
+			}
+		} else if ss.OnDiskIndex > s.onDiskIndex {
```
Comment (stffabi) [inline internal/rsm/statemachine.go]: @lni I don't know if this assumption is right? I thought mit would be consistent with `RecoverRequired` What do you think?

**Comment by stffabi** [comment]
I'll add tests as soon as the PR comes out of draft and is fine for you @lni.

File: internal/rsm/statemachine.go (hunk 1 above)
Comment (lni) [reply internal/rsm/statemachine.go]: I think the logic is correct but it is expressing something like 

```
if A {
} else {
 if A {
  panic()
 }
}
```

I also found the existing code to be easier to read & understand.

When it checks "if ss.Witness || ss.Dummy", it checks to see whether it is a partial snapshot image that does not contains user State Machine data. When true, it chooses the fast path to only apply the snapshot metadata. Everything below that are used to handle situation in which you do have a full snapshot to apply. In your changed version, it is no longer that clearly separated and obvious. For example, for your line 349 and 354, I have to carefully double check what conditions can actually lead to there. 

I'd recommend to just add that check inside the if ss.Witness || ss.Dummy {} block without changing the struct of the remaining part of the StateMachine.recover() method.

For the comments in line 347-348, could you please explicitly mention that this check is actually for situations like data corruption. Thanks.

Comment (stffabi) [reply internal/rsm/statemachine.go]: I see your point regarding the fast path. Nevertheless I have two considerations if we would simply add the new check inside the `if ss.Witness || ss.Dummy {}` block.

- I find it somehow confusing that in this edge case and for a dummy snapshot `recoverRequired` (in its original version) would simply return `true`, although a dummy snapshot can never be recovered.
- What about a shrunk snapshot? In its original version `recoverRequired` would return `false` for a shrunk snapshot during init, which would go to the path to apply the metadata on it. Would it be correct to apply the metadata of a shrunk snapshot which would hurt our new invariant?

Comment (lni) [reply internal/rsm/statemachine.go]: Partial snapshots (including witness and dummy snapshots) are not suppose to reach recoverRequired as in the original implementation they would be handled by that ss.Witness || ss.Dummy {} block. 

That if ss.Witness || ss.Dummy check tests whether the snapshot is a partial one that doesn't have the snapshot content. We should probably include checking for shrunk snapshots as well - as that is another type of partial snapshot. Once confirmed to be a partial snapshot (witness, dummy or shunk snapshot), we can apply its metadata, check our new invariant and exit. 

We can probably run that check again in recoverRequired to make sure we don't accidentally call recoverRequired on partial snapshots in the future. The drawback is that checking whether a snapshot is a shrunk one involves disk IO - it is totally fine for my NVME boxes but might be a concern for some people.

For shrunk snapshot, they are similar to dummy snapshot, the major difference between them is that dummy has this dummy field set to true in its pb.Snapshot record on its creation. A shrunk one doesn't have that, disk IO is involved to check whether shrunk or not. A snapshot for an IOnDiskStateMachine only becomes a shrunk one after it has been fully restored into the state machine. It doesn't have the dummy field set to be true because there is no easy way to atomically swap both of its snapshot file on disk and its pb.Snapshot in LogDB with a shrunk version. Our new invariant still holds because when we have a shrunk snapshot, it implies that its content has been fully restored into the state machine, in that case, on restart (init=true), s.onDiskInitIndex < ss.OnDiskIndex implies corruption.

Comment (stffabi) [reply internal/rsm/statemachine.go]: I've updated the PR, what do you think? I'll fix/update tests as soon as you agree with the state of the PR.

Comment (lni) [reply internal/rsm/statemachine.go]: It looks good to me. One minor issue, please make that comment at line 339 no more than 80 chars per line. Thanks.

Comment (stffabi) [reply internal/rsm/statemachine.go]: Awesome, I've updated the PR with a fix for the comment line and also added some tests.

**Comment by lni** [comment]
Thanks, merged.

**Comment by lni** [comment]
@stffabi all contributors are listed in this project's [AUTHORS](https://github.com/lni/dragonboat/blob/master/AUTHORS) file. do you have an email address that you want to put it there as a more formal kind of identity?

**Comment by stffabi** [comment]
@lni thanks for merging. You can put in "stffabi@pm.me" for the AUTHORS file, thanks.
